### ISSUE TITLE
Impressum missing!

### ISSUE THREAD

**Issue by javahippie** [jug-mz/website#4]
We can't publish the page without an impressum.

**Comment by paulHempel** [comment]
## Things we need to know and/or decide on

- Is the legal form of JUG: a private person, an association/club, ...
- Who represents the JUG? (multiple people possible)
- If the JUG is a association/club: is there a registry entry (legal)
- Is the JUG website as well a blog?
- Do the website needs disclaimer for: external links, responsibility for the content, google analytics, privacy, copyright law, google adsense

### Then we can create with e.g. those websites an impressum:
[Google Search](https://www.google.de/search?q=impressum+generator&cad=h)

**Comment by javahippie** [comment]
These are some valid points. I created all Impressums... Impressi? with e-recht24s generator, but we need to clarify this first. Most legal questions should be clarified easily, for the analytics stuff I am opening a different issue, as this should be discussed seperately
